version: '3.8'
services:
  analyzer:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - ./reports:/app/reports

